export const constants = {
    SESSION: "SESSION",
    USER: "USER",
    JWTSECRET: "ABCXYZSECRETS",
    LOGINSUCCESS: "LOGGED IN SUCCESSFULLY",
    JWTEXPIRY: 60 * 60,
    INVALIDUSERNAMEPWD: "INVALID USERNAME OR PASSWORD",
    DUPLICATEUSERNAME: "THIS USERNAME IS ALREADY IN USE",
    JWTALGO: "HS256",
    SUCCESSCODE: 200,
    SIGNUPSUCCESS: "YOU HAVE SUCCESSFULLY SIGNED UP",
    SIGNUPFAIL: "SIGN UP FAILED",
    LOGOUT: "LOGOUT SUCCESSFULL",
    SOMETHING_WENT_WRONG: "SOMETHING WENT WRONG"
}